In [41]:
import numpy as np

In [42]:
import chardet
with open('tripadvisor_hotel_reviews.csv', 'rb') as rawdata:
    result = chardet.detect(rawdata.read(100000))
result

{'encoding': 'windows-1251', 'confidence': 0.99, 'language': 'Russian'}

In [43]:
import pandas as pd
df = pd.read_csv('tripadvisor_hotel_reviews.csv', encoding='windows-1251')
df.head

<bound method NDFrame.head of     selection1_name,"selection1_selection2_name","selection1_selection2_selection3","selection1_selection2_selection3_url"
0    Глэмпинг Доброе,"Плюсы: Очень красивая заповед...                                                                    
1    Глэмпинг Доброе,"Ездили в глэмпинг Доброе комп...                                                                    
2    Глэмпинг Доброе,"Из плюсов: красивая заповедна...                                                                    
3    Глэмпинг Доброе,"Красиво, дикая природа с идеа...                                                                    
4    Глэмпинг Доброе,"Все отлично, но с газом надо ...                                                                    
..                                                 ...                                                                    
100  Eko-camping SFERA,"Сама по себе идея вообще ог...                                                       

In [44]:
df.rename(columns = {'selection1_name,"selection1_selection2_name","selection1_selection2_selection3","selection1_selection2_selection3_url"': 'reviews'}, inplace = True)
df

reviews
0    Глэмпинг Доброе,"Плюсы: Очень красивая заповед...
1    Глэмпинг Доброе,"Ездили в глэмпинг Доброе комп...
2    Глэмпинг Доброе,"Из плюсов: красивая заповедна...
3    Глэмпинг Доброе,"Красиво, дикая природа с идеа...
4    Глэмпинг Доброе,"Все отлично, но с газом надо ...
..                                                 ...
100  Eko-camping SFERA,"Сама по себе идея вообще ог...
101  Eko-camping SFERA,"При заселении проводили нас...
102  Eko-camping SFERA,"эко кемпинг SFERA - купол п...
103                          СПА ЛЕС глэмпинг,"","",""
104                        Глэмпинг Под Небом,"","",""

[105 rows x 1 columns]

In [45]:
places = []
reviews = []

for element in range(df.size):
    place = df['reviews'][element].split('"')[0]
    review = df['reviews'][element].split('"')[1]
    places.append(place)
    reviews.append(review)
    
df = pd.DataFrame({'places': places, 'reviews':reviews})
df

places                                            reviews
0       Глэмпинг Доброе,  Плюсы: Очень красивая заповедная зона, просыпа...
1       Глэмпинг Доброе,  Ездили в глэмпинг Доброе компанией в конце апр...
2       Глэмпинг Доброе,  Из плюсов: красивая заповедная зона, потрясающ...
3       Глэмпинг Доброе,  Красиво, дикая природа с идеальным комфортом, ...
4       Глэмпинг Доброе,  Все отлично, но с газом надо что то делать. Мо...
..                   ...                                                ...
100   Eko-camping SFERA,  Сама по себе идея вообще огонь (если говорить ...
101   Eko-camping SFERA,  При заселении проводили нас в наш геокупол #1 ...
102   Eko-camping SFERA,  эко кемпинг SFERA - купол плюсы - красивая при...
103    СПА ЛЕС глэмпинг,                                                   
104  Глэмпинг Под Небом,                                                   

[105 rows x 2 columns]

In [46]:
df1 = df.copy()
places1 = []
data = {}

for row in range(len(df1.index)):
    if df1.iat[row, 0] not in places1:
        places1.append(df1.iat[row, 0])
        df2 = df1[df1['places'] == df1.iat[row, 0]]
#         print(df2)
        tem = []
        for i in range(len(df2.index)):
            tem.append(df2.iat[i, 1].lower())
        data[df1.iat[row, 0]] = tem

reviews1 = []*len(places1)

for i in range(len(places1)):
    reviews1.append(data[places1[i]])
#     reviews1[i] = ' '.join(reviews1[i])

In [47]:
for i in range(len(places1)):
    places1[i] = places1[i][:-1]

In [48]:
new = pd.DataFrame({'places': places1, 'collected_reviews': reviews1})

In [49]:
new

places  \
0                 Глэмпинг Доброе   
1           Глэмпинг на озере Сиг   
2            Глэмпинг Видно Озеро   
3                Глэмпинг Vezzika   
4              ЛЕС Глэмпинг и спа   
5                Глэмпинг NewCamp   
6             Urman Camp Глэмпинг   
7            Велна Эко Спа Резорт   
8              Глэмпинг Под небом   
9                     Гуляй-Город   
10         Глэмпинг Китовый Берег   
11                 Zelenaya Tropa   
12                    Мамонт Camp   
13                          Скала   
14              Халактырский пляж   
15                          Шикша   
16           База отдыха Салокюля   
17                 Дальний кордон   
18                        Айвенго   
19                     Папоротник   
20               Polyana Glamping   
21             Кемпинг Лес и Море   
22  Майтри Кэмп на Финском Заливе   
23         Глэмпинг Северный Крым   
24         Трувор Глэмпинг Валдай   
25          Глемпинг Старый Сивух   
26              Долина мечтателей   
27              Eko-camping SFERA   
28               СПА ЛЕС глэмпинг   
29             Глэмпинг Под Небом   

                                    collected_reviews  
0   [плюсы: очень красивая заповедная зона, просып...  
1   [отдыхала одна с двумя детьми. очень повезло с...  
2   [забронировал проживание в глэмпинге , случайн...  
3   [плюсы: - хорошее и красивое местоположение ми...  
4   [решили мы посетить это чудесное место , забро...  
5   [глэмпинг находится близ посёлка эссойла, в со...  
6   [приехали в глэмпинг к 5 попросили заранее зат...  
7   [мне есть с чем сравнивать, поэтому посетив за...  
8   [отличные условия проживания, очень отзывчивый...  
9   [приехали сегодня после дороги и музея в серпу...  
10  [мы не могли и предположить, что получим столь...  
11  [итак, вы платите 30 000 рублей за две ночи, б...  
12  [потрясающее единение комфорта, уюта, невероят...  
13  [проживали в домике с видом на море. ощутил по...  
14                                                 []  
15  [прекрасное места для отдыха душой и телом. бе...  
16  [отдыхали в этом чудесном местечке неделю в се...  
17  [турбаза находится недалеко от москвы - пример...  
18  [выбрали отдых на алтае как альтернативу поезд...  
19  [решили отдохнуть в карелии. выбрали это место...  
20  [потрясающая локация, идеальное место, чтобы п...  
21  [отдыхали 3 ночи, с малышом 6 мес и собакой дж...  
22  [место очень красивое, живописное! финский зал...  
23  [не реклама...:)...довелось проездом сутки на ...  
24  [атмосферное, уютное и очень душевное место. у...  
25  [выходные пролетели как маленькая жизнь! они б...  
26                                                 []  
27  [были два дня назад. место волшебное - ощущени...  
28                                                 []  
29                                                 []

## Cleaning data

In [31]:
!pip install regex

In [50]:
import re
import string

In [51]:
import nltk
import pymorphy2
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [52]:
stop = stopwords.words('russian')
stop.remove('хорошо')
stop.append('это')
stop.append('место')
stop.append('персонал')

from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def preprocessing(review):
    
    # data cleaning
    review = review.lower()
    review = re.sub(r'((www.\.\[^\s]+)|(https?://[^\s]+))', r'', review)
    review = re.sub(r'@[^\s]+', r'', review)
    review = re.sub(r'\W*\b\w{1,3}\b', r'', review)
    
#     for word in review:
#         word = re.sub(r'((www.\.\[^\s]+)|(https?://[^\s]+))', r'', word)
#         word = re.sub(r'@[^\s]+', r'', word)
#         word = re.sub(r'\W*\b\w{1,3}\b', r'', word)
        
#     review = re.sub('\-\s\r\n\s{1,}|\-\s\r\n|\r\n', '', review) #deleting newlines and line-breaks
#     review = re.sub('[.,:;%©?*,!@#$%^&()\d]|[+=]|[[]|[]]|[/]|"|\s{2,}|-', ' ', review) #deleting symbols
    
    token = nltk.word_tokenize(review)
    
    review = [word for word in token if (word not in stop and word not in string.punctuation 
                                         and word != "' '" and word != "``" and word != "''" and word.isnumeric() == False) ]
    
    review = ' '.join(pymorphy2.MorphAnalyzer().parse(word)[0].normal_form for word in review)
#     review = [lemmatizer.lemmatize(word) for word in review]
#     review = ' '.join(review)
    
    return review 

In [53]:
def prepareOnePlaceReviews(reviews):
    for i in range(len(reviews)):
        reviews[i] = preprocessing(reviews[i])
    return reviews

In [57]:
new.iat[23,1]

['не реклама...:)...довелось проездом сутки на базе провести. как управляющий турбазой в карелии.....минусов у замошье - нет....плюсы..1) -разнесли заезд\\выезд (час пик для любой турбазы) на два часа для разных домиков..2)-главный плюс- все новое...домики, инвентарь, даже, деревья посаженные...3)-организована парковка авто гостей...4)-отдых для семей с детьми - ферма со ',
 'в последний день пребывания, перестало работать кафе, причины не объяснили. завтрак, который, указан на сайте, что ']

In [58]:
st = prepareOnePlaceReviews(new.iat[23,1])
st

['реклама ... ... довестись проезд сутки база провести управлять турбаза карелия ..... минус замоший .... плюс -разнести заезд\\выезд любой турбаза час разный домик -главный плюс новый ... домик инвентарь дерево посадить -организовать парковка авто гость -отдых семья ребёнок ферма',
 'последний день пребывание перестать работать кафе причина объяснить завтрак который указать сайт']

In [59]:
new['collected_reviews'] = new['collected_reviews'].apply(lambda reviews: prepareOnePlaceReviews(reviews))

In [60]:
new

places  \
0                 Глэмпинг Доброе   
1           Глэмпинг на озере Сиг   
2            Глэмпинг Видно Озеро   
3                Глэмпинг Vezzika   
4              ЛЕС Глэмпинг и спа   
5                Глэмпинг NewCamp   
6             Urman Camp Глэмпинг   
7            Велна Эко Спа Резорт   
8              Глэмпинг Под небом   
9                     Гуляй-Город   
10         Глэмпинг Китовый Берег   
11                 Zelenaya Tropa   
12                    Мамонт Camp   
13                          Скала   
14              Халактырский пляж   
15                          Шикша   
16           База отдыха Салокюля   
17                 Дальний кордон   
18                        Айвенго   
19                     Папоротник   
20               Polyana Glamping   
21             Кемпинг Лес и Море   
22  Майтри Кэмп на Финском Заливе   
23         Глэмпинг Северный Крым   
24         Трувор Глэмпинг Валдай   
25          Глемпинг Старый Сивух   
26              Долина мечтателей   
27              Eko-camping SFERA   
28               СПА ЛЕС глэмпинг   
29             Глэмпинг Под Небом   

                                    collected_reviews  
0   [плюс очень красивый заповедный зона просыпать...  
1   [отдыхать один два ребёнок очень повезти погод...  
2   [забронировать проживание глэмпинг, случайно о...  
3   [плюс хороший красивый местоположение минус ин...  
4   [решить посетить чудесный забронировать значит...  
5   [глэмпинг находиться близ посёлок эссойло сосн...  
6   [приехать глэмпинг попросить заранее затопить ...  
7   [сравнивать поэтому посетить загородный-отель ...  
8   [отличный условие проживание очень отзывчивый ...  
9   [приехать сегодня дорога музей серпухов доброж...  
10  [мочь предположить получить столько новый эмоц...  
11  [итак платить рубль ночь доплачивать три килог...  
12  [потрясать единение комфорт уют невероятно вку...  
13  [проживать домик вид море ощутить полный идилл...  
14                                                 []  
15  [прекрасный место отдых душа тело бескрайний в...  
16  [отдыхать чудесный местечко неделя сентябрь се...  
17  [турбаза находиться недалеко москва примерно м...  
18  [выбрать отдых алтай альтернатива поездка море...  
19  [решить отдохнуть карелия выбрать думать отдох...  
20  [потрясать локация идеальный провести время ка...  
21  [отдыхать ночь малыш собака джек рассесть терь...  
22  [очень красивый живописный финский залив велик...  
23  [реклама ... ... довестись проезд сутки база п...  
24  [атмосферный уютный очень душевный уединение с...  
25  [выходной пролететь маленький жизнь насыщенный...  
26                                                 []  
27  [назад волшебный ощущение побывать настоящий с...  
28                                                 []  
29                                                 []

In [61]:
new['collected_reviews'][0]

['плюс очень красивый заповедный зона просыпаться вид море засыпать волна пожалуй самый необычный отпуск вроде жить палатка минимальный набор необходимый комфортный пребывание идеальный вариант мечтать сходить поход палатка перспектива ходить туалет ёлка точно очень расслаблять помогать отдохнуть городской суета ярко минус готовый глэмпинг тяжело добраться неподготовленный человек добраться два способ пешком моторный лодка лодка стоить поездка конец сам глэмпинг причал деревянный помост поэтому лодка прийтись прыгать вода забираться лодка вода',
 'ездить глэмпинг добрый компания конец апрель поскольку апрель действительно выдаться холодный делать больший скидка этот место откинуть наш погодный невезение сильно разочаровать соотношение',
 'плюс красивый заповедный зона потрясать закат вкусный мидия блинчик завтрак очень приятный вежливый молодой человек который собственно приносить завтрак минус везде грязненький очень бросаться глаз жутко неудобный скрипучий кровать который спина болет

## Machine Learning

In [62]:
import numpy as np
import re
from tensorflow.keras.layers import Dense, LSTM, Input, Dropout, Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [63]:
f = open('C:\\Users\\anast\\jupyter_notebook\\Anastasia_Notes\\Project TripAdvisor\\train_data_true.txt', 'r', encoding='utf-8')
texts_true = f.readlines()
texts_true[0] = texts_true[0].replace('\ufeff','')

In [64]:
f = open('C:\\Users\\anast\\jupyter_notebook\\\Anastasia_Notes\\Project TripAdvisor\\train_data_false.txt', 'r', encoding='utf-8')
texts_false = f.readlines()
texts_false[0] = texts_false[0].replace('\ufeff','')

In [65]:
texts = texts_true + texts_false
count_true = len(texts_true)
count_false = len(texts_false)
total_lines = count_true + count_false
print(count_true,count_false,total_lines)

110 109 219


In [66]:
maxWordsCount = 2000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»', lower=True, split=' ', char_level=False)
tokenizer. fit_on_texts (texts)

In [67]:
data = tokenizer.texts_to_sequences(texts)
max_text_len = 10
data_pad = pad_sequences(data, maxlen=max_text_len)
print(data_pad)
print(data_pad.shape)

[[ 226   57    2 ...  228  229  230]
 [   0    5  231 ...  234    3   77]
 [ 235    3   77 ...    5  237  238]
 ...
 [   0    0    0 ... 1048    2 1049]
 [   0    0    0 ...  196 1050 1051]
 [   0    0    0 ...    8  189  215]]
(219, 10)


In [68]:
X = data_pad
Y = np.array([[1, 0]]*count_true + [[0, 1]]*count_false)
print(X.shape, Y.shape)

(219, 10) (219, 2)


In [69]:
indeces = np.random.choice(X.shape[0], size=X.shape[0], replace=False)
X = X[indeces]
Y = Y[indeces]

In [70]:
model = Sequential()
model.add(Embedding(maxWordsCount, 128, input_length = max_text_len))
model.add(LSTM(64, activation='tanh', return_sequences=True))
model.add(LSTM(32, activation='tanh'))
model.add(Dense(2, activation='softmax'))
model.summary()
model.compile(loss='categorical_crossentropy', metrics = ['accuracy'], optimizer = Adam(0.0001))

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 128)           256000    
                                                                 
 lstm (LSTM)                 (None, 10, 64)            49408     
                                                                 
 lstm_1 (LSTM)               (None, 32)                12416     
                                                                 
 dense (Dense)               (None, 2)                 66        
                                                                 
Total params: 317,890
Trainable params: 317,890
Non-trainable params: 0
_________________________________________________________________


In [71]:
history = model.fit(X, Y, batch_size=32, epochs=50)

Epoch 1/50
7/7 [==============================] - 2s 7ms/step - loss: 0.6912 - accuracy: 0.6256
Epoch 2/50
7/7 [==============================] - 0s 8ms/step - loss: 0.6888 - accuracy: 0.6941
Epoch 3/50
7/7 [==============================] - 0s 8ms/step - loss: 0.6865 - accuracy: 0.7169
Epoch 4/50
7/7 [==============================] - 0s 8ms/step - loss: 0.6837 - accuracy: 0.7717
Epoch 5/50
7/7 [==============================] - 0s 8ms/step - loss: 0.6809 - accuracy: 0.7945
Epoch 6/50
7/7 [==============================] - 0s 8ms/step - loss: 0.6770 - accuracy: 0.7991
Epoch 7/50
7/7 [==============================] - 0s 7ms/step - loss: 0.6726 - accuracy: 0.8128
Epoch 8/50
7/7 [==============================] - 0s 8ms/step - loss: 0.6670 - accuracy: 0.8265
Epoch 9/50
7/7 [==============================] - 0s 7ms/step - loss: 0.6608 - accuracy: 0.8265
Epoch 10/50
7/7 [==============================] - 0s 7ms/step - loss: 0.6527 - accuracy: 0.8265
Epoch 11/50
7/7 [======================

In [83]:
strings = new.shape[0]

In [73]:
def res_to_string(result):
    count_all_positive = 0
    count_all_negative = 0
    if (result[0][0] < result[0][1]):
        count_all_negative += 1;
    elif (result[0][0]) > (result[0][1]):
        count_all_positive += 1;
    return [count_all_positive,count_all_negative]

In [78]:
tup_pos = []
tup_neg = []

for i in range(strings):
    a = 0
    b = 0
    for j in range(len(new.iat[i,1])):
        t = new.iat[i,1][j]
        data = tokenizer.texts_to_sequences([t])
        data_pad = pad_sequences(data, maxlen = max_text_len)
        res = model.predict(data_pad)
        a += res_to_string(res)[0]
        b += res_to_string(res)[1]
    tup_pos.append(a)
    tup_neg.append(b)

1/1 [==============================] - 0s 16ms/step


In [82]:
new['Number of positive reviews'] = tup_pos
new['Number of negative reviews'] = tup_neg
for i in range(30):
    if new.iat[i,1] == ['']:
        new.iat[i,3] = new.iat[i,2]
new

places  \
0                 Глэмпинг Доброе   
1           Глэмпинг на озере Сиг   
2            Глэмпинг Видно Озеро   
3                Глэмпинг Vezzika   
4              ЛЕС Глэмпинг и спа   
5                Глэмпинг NewCamp   
6             Urman Camp Глэмпинг   
7            Велна Эко Спа Резорт   
8              Глэмпинг Под небом   
9                     Гуляй-Город   
10         Глэмпинг Китовый Берег   
11                 Zelenaya Tropa   
12                    Мамонт Camp   
13                          Скала   
14              Халактырский пляж   
15                          Шикша   
16           База отдыха Салокюля   
17                 Дальний кордон   
18                        Айвенго   
19                     Папоротник   
20               Polyana Glamping   
21             Кемпинг Лес и Море   
22  Майтри Кэмп на Финском Заливе   
23         Глэмпинг Северный Крым   
24         Трувор Глэмпинг Валдай   
25          Глемпинг Старый Сивух   
26              Долина мечтателей   
27              Eko-camping SFERA   
28               СПА ЛЕС глэмпинг   
29             Глэмпинг Под Небом   

                                    collected_reviews  \
0   [плюс очень красивый заповедный зона просыпать...   
1   [отдыхать один два ребёнок очень повезти погод...   
2   [забронировать проживание глэмпинг, случайно о...   
3   [плюс хороший красивый местоположение минус ин...   
4   [решить посетить чудесный забронировать значит...   
5   [глэмпинг находиться близ посёлок эссойло сосн...   
6   [приехать глэмпинг попросить заранее затопить ...   
7   [сравнивать поэтому посетить загородный-отель ...   
8   [отличный условие проживание очень отзывчивый ...   
9   [приехать сегодня дорога музей серпухов доброж...   
10  [мочь предположить получить столько новый эмоц...   
11  [итак платить рубль ночь доплачивать три килог...   
12  [потрясать единение комфорт уют невероятно вку...   
13  [проживать домик вид море ощутить полный идилл...   
14                                                 []   
15  [прекрасный место отдых душа тело бескрайний в...   
16  [отдыхать чудесный местечко неделя сентябрь се...   
17  [турбаза находиться недалеко москва примерно м...   
18  [выбрать отдых алтай альтернатива поездка море...   
19  [решить отдохнуть карелия выбрать думать отдох...   
20  [потрясать локация идеальный провести время ка...   
21  [отдыхать ночь малыш собака джек рассесть терь...   
22  [очень красивый живописный финский залив велик...   
23  [реклама ... ... довестись проезд сутки база п...   
24  [атмосферный уютный очень душевный уединение с...   
25  [выходной пролететь маленький жизнь насыщенный...   
26                                                 []   
27  [назад волшебный ощущение побывать настоящий с...   
28                                                 []   
29                                                 []   

    Number of positive reviews  Number of negative reviews  
0                            5                           0  
1                            3                           2  
2                            0                           2  
3                            4                           0  
4                            3                           2  
5                            0                           1  
6                            4                           1  
7                            4                           1  
8                            3                           2  
9                            5                           0  
10                           0                           1  
11                           4                           1  
12                           3                           0  
13                           5                           0  
14                           0                           0  
15                           2                           2  
16                           4                           1  
17           